name: "Create IIS Backup"
description: "Creates a versioned backup of the target IIS deployment directory."
inputs:
  deploy_target_path:
    description: "Target IIS deployment directory to backup"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Create Backup Folder"
      shell: pwsh
      run: |
        $deployPath = "${{ inputs.deploy_target_path }}"
        $parentDir = Split-Path $deployPath -Parent
        $backupsBase = Join-Path $parentDir "backups"

        if (!(Test-Path $backupsBase)) {
          New-Item -ItemType Directory -Path $backupsBase | Out-Null
        }

        $rawName = Split-Path $deployPath -Leaf
        $siteName = ($rawName -replace "-\d{4}-\d{2}-\d{2}-\d+$", "")

        # Carpeta específica del proyecto dentro de /backups
        $backupRoot = Join-Path $backupsBase "${siteName}_backups"

        if (!(Test-Path $backupRoot)) {
          New-Item -ItemType Directory -Path $backupRoot | Out-Null
        }


        # Obtener la última fecha y hora de modificación del deployment actual
        if (Test-Path $deployPath) {
          $lastModifiedItem = Get-ChildItem -Recurse -Path $deployPath -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1

          if ($lastModifiedItem) {
            $dateTime = $lastModifiedItem.LastWriteTime.ToString("yyyy-MM-dd")
            Write-Host "📅 Última modificación detectada: $dateTime"
          } else {
            Write-Host "⚠️ No se encontraron archivos dentro del deployment. Usando fecha actual."
            $dateTime = (Get-Date).ToString("yyyy-MM-dd")
          }
        } else {
          Write-Host "⚠️ Ruta de deployment no encontrada. Usando fecha actual."
          $dateTime = (Get-Date).ToString("yyyy-MM-dd")
        }

        $i = 1
        while (Test-Path "$backupRoot\$siteName-$dateTime-$i") { $i++ }
        $backupFolder = "$backupRoot\$siteName-$dateTime-$i"

        Write-Host "📦 Creando carpeta de backup: $backupFolder"
        New-Item -ItemType Directory -Path $backupFolder | Out-Null

        if (Test-Path $deployPath) {
          Write-Host "📂 Copiando desde $deployPath → $backupFolder"
          Copy-Item -Path "$deployPath\*" -Destination $backupFolder -Recurse -Force
          Write-Host "✅ Backup completado con éxito."
        } else {
          Write-Host "⚠️ No se encontró el deployment original, no se generó backup."
        }
