name: "Build & Test app"
description: "Construye la aplicación y testea"

inputs:
  has_tests:
    description: "Confirmar si la app tiene tests para ejecutarlos"
    required: true
    type: bool
  project_path:
    description: "Ruta al .csproj"
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore app
      shell: bash
      run: |
        dotnet restore ${{ inputs.project_path }}

    - name: Build the app
      shell: bash
      run: |
        dotnet build ${{ inputs.project_path }} --configuration Release

    - name: Test the app
      if: ${{ inputs.has_tests == true }}
      shell: bash
      run: |
        dotnet test ${{ inputs.project_path }}